// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.API.Data;

#nullable disable

namespace Products.API.Data.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260209091752_AddIdempotentConsumer")]
    partial class AddIdempotentConsumer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mango.Infrastructure.ProcessedMessages.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_date");

                    b.HasKey("Id")
                        .HasName("pk_processed_message");

                    b.HasIndex("Id", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_processed_message_id_name");

                    b.ToTable("processed_message", (string)null);
                });

            modelBuilder.Entity("Products.API.Entities.CatalogBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.HasKey("Id")
                        .HasName("pk_catalog_brands");

                    b.ToTable("catalog_brands", (string)null);
                });

            modelBuilder.Entity("Products.API.Entities.CatalogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_catalog_types");

                    b.ToTable("catalog_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Appetizer"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Entree"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Dessert"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Bread"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Beverage"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Side"
                        });
                });

            modelBuilder.Entity("Products.API.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer")
                        .HasColumnName("available_stock");

                    b.Property<int?>("CatalogBrandId")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_brand_id");

                    b.Property<int?>("CatalogTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_type_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CatalogBrandId")
                        .HasDatabaseName("ix_products_catalog_brand_id");

                    b.HasIndex("CatalogTypeId")
                        .HasDatabaseName("ix_products_catalog_type_id");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("970afb7e-5616-46c4-b3fa-f9abb62928db"),
                            AvailableStock = 30,
                            CatalogTypeId = 1,
                            CategoryName = "Appetizer",
                            Description = "Crispy golden triangular pastries filled with spiced potatoes and peas. A beloved Indian street food appetizer served with mint and tamarind chutneys.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Samosa",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = new Guid("348cc1a0-707b-4e1b-9700-de40d54acd31"),
                            AvailableStock = 30,
                            CatalogTypeId = 1,
                            CategoryName = "Appetizer",
                            Description = "Cubes of fresh cottage cheese marinated in yogurt and aromatic spices, grilled to perfection in a tandoor oven. Served with fresh salad and mint chutney.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Paneer Tikka",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = new Guid("bc047267-5eb9-4681-b489-4473ccd00a87"),
                            AvailableStock = 30,
                            CatalogTypeId = 3,
                            CategoryName = "Dessert",
                            Description = "A delightful homemade pie with a buttery crust filled with seasonal fruits and topped with a golden lattice. Served warm with vanilla ice cream.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Sweet Pie",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = new Guid("7e51b0af-8c5f-4721-99bb-4aaf8fc4822e"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "A spicy mashed vegetable curry served with buttery toasted bread rolls. This popular Mumbai street food is garnished with fresh onions, cilantro, and a squeeze of lemon.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Pav Bhaji",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789001"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Tender pieces of tandoori chicken simmered in a rich, creamy tomato sauce with aromatic spices. A classic North Indian dish served with basmati rice.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Butter Chicken",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789002"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Fragrant basmati rice layered with spiced chicken, caramelized onions, and saffron. Slow-cooked to perfection and served with cooling raita.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Chicken Biryani",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789003"),
                            AvailableStock = 30,
                            CatalogTypeId = 4,
                            CategoryName = "Bread",
                            Description = "Soft, pillowy flatbread brushed with garlic butter and fresh herbs. Baked in our traditional clay tandoor oven until perfectly golden.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Garlic Naan",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789004"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Half chicken marinated overnight in yogurt and traditional spices, then roasted in a clay tandoor. Served sizzling with grilled vegetables.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Tandoori Chicken",
                            Price = 17.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789005"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Tender lamb pieces braised in a rich Kashmiri sauce with whole spices and aromatic herbs. A traditional recipe passed down through generations.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Lamb Rogan Josh",
                            Price = 22.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789006"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Fresh cottage cheese cubes in a vibrant spinach puree flavored with garlic and ginger. A nutritious vegetarian favorite.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Palak Paneer",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789007"),
                            AvailableStock = 30,
                            CatalogTypeId = 5,
                            CategoryName = "Beverage",
                            Description = "A refreshing yogurt-based drink blended with ripe Alphonso mangoes and a hint of cardamom. The perfect complement to any spicy meal.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Mango Lassi",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789008"),
                            AvailableStock = 30,
                            CatalogTypeId = 3,
                            CategoryName = "Dessert",
                            Description = "Soft milk dumplings deep-fried to golden perfection and soaked in rose-scented sugar syrup. Served warm with a drizzle of cream.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Gulab Jamun",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789009"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Grilled chicken pieces in a luscious, creamy tomato-based curry sauce. Britain's favorite Indian dish, rich with warming spices.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Chicken Tikka Masala",
                            Price = 18.49m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789010"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Mixed seasonal vegetables simmered in a mild, creamy cashew and coconut sauce. A gentle introduction to Indian cuisine.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Vegetable Korma",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789011"),
                            AvailableStock = 30,
                            CatalogTypeId = 1,
                            CategoryName = "Appetizer",
                            Description = "Crispy deep-fried fritters made with sliced onions and gram flour, seasoned with cumin and coriander. Perfect as a starter or snack.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Onion Bhaji",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789012"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Fresh catch of the day cooked in a tangy tamarind and coconut curry from the coastal regions of South India. Served with steamed rice.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Fish Curry",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789013"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Black lentils slow-cooked overnight with butter and cream, creating a rich and hearty vegetarian dish. A Punjabi specialty.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Dal Makhani",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789014"),
                            AvailableStock = 30,
                            CatalogTypeId = 1,
                            CategoryName = "Appetizer",
                            Description = "Minced chicken mixed with fresh herbs and spices, molded onto skewers and grilled in tandoor. Served with mint chutney and onion rings.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Chicken Seekh Kebab",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789015"),
                            AvailableStock = 30,
                            CatalogTypeId = 6,
                            CategoryName = "Side",
                            Description = "Cool and refreshing yogurt-based condiment with cucumber, tomatoes, and aromatic spices. Essential for balancing spicy dishes.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Raita",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789016"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Cauliflower and potatoes stir-fried with turmeric, cumin, and fresh ginger. A comforting dry vegetable dish from North India.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Aloo Gobi",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789017"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Succulent tiger prawns cooked in a spicy masala sauce with onions, tomatoes, and aromatic coastal spices.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Prawn Masala",
                            Price = 23.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789018"),
                            AvailableStock = 30,
                            CatalogTypeId = 4,
                            CategoryName = "Bread",
                            Description = "Fluffy naan bread stuffed with melted mozzarella and cheddar cheese. Baked until golden and served hot from the tandoor.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Cheese Naan",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789019"),
                            AvailableStock = 30,
                            CatalogTypeId = 3,
                            CategoryName = "Dessert",
                            Description = "Soft cheese patties soaked in sweetened, thickened milk flavored with cardamom and saffron. Garnished with pistachios.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Rasmalai",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789020"),
                            AvailableStock = 30,
                            CatalogTypeId = 5,
                            CategoryName = "Beverage",
                            Description = "Traditional Indian spiced tea brewed with cinnamon, cardamom, ginger, and cloves. Served with warm milk.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Masala Chai",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789021"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Spiced minced lamb cooked with peas, onions, and tomatoes. A hearty dish perfect with naan or rice.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Lamb Keema",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789022"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Chickpeas simmered in a tangy tomato-based sauce with traditional North Indian spices. A protein-rich vegetarian favorite.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Chana Masala",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789023"),
                            AvailableStock = 30,
                            CatalogTypeId = 1,
                            CategoryName = "Appetizer",
                            Description = "Crispy thin lentil wafers served with an assortment of chutneys. A traditional accompaniment to any Indian meal.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Pappadum",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789024"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Slow-cooked goat meat in a rich, aromatic gravy with whole spices. A traditional recipe that melts in your mouth.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Mutton Curry",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789025"),
                            AvailableStock = 30,
                            CatalogTypeId = 3,
                            CategoryName = "Dessert",
                            Description = "Traditional Indian ice cream made with reduced milk, flavored with cardamom and pistachios. Denser and creamier than regular ice cream.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Kulfi",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789026"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Tender chicken pieces cooked in a flavorful spinach and mustard green sauce with garlic and ginger.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Saag Chicken",
                            Price = 17.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789027"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Fragrant basmati rice layered with mixed vegetables, fried onions, and aromatic spices. A vegetarian feast in every bite.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/11.jpg",
                            Name = "Vegetable Biryani",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789028"),
                            AvailableStock = 30,
                            CatalogTypeId = 2,
                            CategoryName = "Entree",
                            Description = "Fiery Goan curry with tender lamb pieces in a tangy, spicy sauce made with vinegar and chili. For those who love heat!",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/13.jpg",
                            Name = "Lamb Vindaloo",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789029"),
                            AvailableStock = 30,
                            CatalogTypeId = 6,
                            CategoryName = "Side",
                            Description = "Sweet and tangy condiment made from ripe mangoes, sugar, and spices. The perfect accompaniment to any curry dish.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/14.jpg",
                            Name = "Mango Chutney",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abcd-123456789030"),
                            AvailableStock = 30,
                            CatalogTypeId = 3,
                            CategoryName = "Dessert",
                            Description = "Creamy Indian rice pudding slow-cooked with milk, sugar, and cardamom. Garnished with almonds, pistachios, and saffron strands.",
                            ImageUrl = "https://phanhaidang.blob.core.windows.net/mango/12.jpg",
                            Name = "Kheer",
                            Price = 6.99m
                        });
                });

            modelBuilder.Entity("Products.API.Entities.Product", b =>
                {
                    b.HasOne("Products.API.Entities.CatalogBrand", "CatalogBrand")
                        .WithMany()
                        .HasForeignKey("CatalogBrandId")
                        .HasConstraintName("fk_products_catalog_brands_catalog_brand_id");

                    b.HasOne("Products.API.Entities.CatalogType", "CatalogType")
                        .WithMany()
                        .HasForeignKey("CatalogTypeId")
                        .HasConstraintName("fk_products_catalog_types_catalog_type_id");

                    b.Navigation("CatalogBrand");

                    b.Navigation("CatalogType");
                });
#pragma warning restore 612, 618
        }
    }
}
