// <auto-generated />
using System;
using Coupons.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coupons.API.Data.Migrations
{
    [DbContext(typeof(CouponDbContext))]
    partial class CouponDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coupons.API.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.HasKey("Id")
                        .HasName("pk_coupons");

                    b.ToTable("coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fcc1596e-7dd5-486f-a498-8eacad314302"),
                            Code = "10OFF",
                            DiscountAmount = 10m
                        },
                        new
                        {
                            Id = new Guid("9bb19343-3ba8-492c-8786-469ec240d266"),
                            Code = "20OFF",
                            DiscountAmount = 20m
                        },
                        new
                        {
                            Id = new Guid("50aa664d-2984-4159-a0ae-4e3eeaf416c1"),
                            Code = "30OFF",
                            DiscountAmount = 30m
                        },
                        new
                        {
                            Id = new Guid("b5a6b6d6-8c2f-4b2e-8f3e-2f5d3e4f5d3e"),
                            Code = "40OFF",
                            DiscountAmount = 40m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
